RENAME TABLE `cosmetic_product` TO `cosmetic_item`;
ALTER TABLE `checkin_item` CHANGE COLUMN `product_id` `cosmetic_id` INT NOT NULL;
ALTER TABLE `checkin_item` CHANGE COLUMN `product_name` `cosmetic_name` VARCHAR(128) NOT NULL;
ALTER TABLE `checkin_item` CHANGE COLUMN `product_image` `cosmetic_image` VARCHAR(255) DEFAULT NULL;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(64) NOT NULL,
  `avatar` VARCHAR(255) DEFAULT NULL,
  `account` VARCHAR(64) DEFAULT NULL,
  `password` VARCHAR(64) DEFAULT NULL,
  `age` INT DEFAULT NULL,
  `gender` VARCHAR(16) DEFAULT NULL,
  `skin_type` VARCHAR(32) DEFAULT NULL,
  `skin_goal` VARCHAR(128) DEFAULT NULL,
  `bio` VARCHAR(255) DEFAULT NULL,
  `is_delete` INT NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `cosmetic_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `brand` VARCHAR(128) DEFAULT NULL,
  `category` VARCHAR(32) NOT NULL,
  `image_url` VARCHAR(255) DEFAULT NULL,
  `production_date` DATE DEFAULT NULL,
  `expire_date` DATE DEFAULT NULL,
  `effect_tag` VARCHAR(128) DEFAULT NULL,
  `ingredient` VARCHAR(255) DEFAULT NULL,
  `use_period` VARCHAR(32) DEFAULT NULL,
  `note` VARCHAR(255) DEFAULT NULL,
  `is_delete` INT NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `checkin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `checkin_date` DATE NOT NULL,
  `skin_status` VARCHAR(64) DEFAULT NULL,
  `hydration_score` INT DEFAULT NULL,
  `oiliness_score` INT DEFAULT NULL,
  `sensitivity_score` INT DEFAULT NULL,
  `note` VARCHAR(255) DEFAULT NULL,
  `is_delete` INT NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_checkin_user_date` (`user_id`, `checkin_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `checkin_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `checkin_id` INT NOT NULL,
  `cosmetic_id` INT NOT NULL,
  `cosmetic_name` VARCHAR(128) NOT NULL,
  `cosmetic_image` VARCHAR(255) DEFAULT NULL,
  `category` VARCHAR(32) NOT NULL,
  `step_order` INT NOT NULL DEFAULT 1,
  `is_delete` INT NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `skin_test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `test_date` DATE NOT NULL,
  `skin_type` VARCHAR(32) DEFAULT NULL,
  `hydration_score` INT DEFAULT NULL,
  `oiliness_score` INT DEFAULT NULL,
  `sensitivity_score` INT DEFAULT NULL,
  `pore_score` INT DEFAULT NULL,
  `blackhead_score` INT DEFAULT NULL,
  `summary` VARCHAR(255) DEFAULT NULL,
  `advice` VARCHAR(255) DEFAULT NULL,
  `is_delete` INT NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `user`
  ADD COLUMN IF NOT EXISTS `account` VARCHAR(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `password` VARCHAR(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `skin_type` VARCHAR(32) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `skin_goal` VARCHAR(128) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `bio` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `is_delete` INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `cosmetic_item`
  ADD COLUMN IF NOT EXISTS `image_url` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `production_date` DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `expire_date` DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `effect_tag` VARCHAR(128) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `ingredient` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `use_period` VARCHAR(32) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `note` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `is_delete` INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `checkin`
  ADD COLUMN IF NOT EXISTS `skin_status` VARCHAR(64) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `hydration_score` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `oiliness_score` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `sensitivity_score` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `note` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `is_delete` INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `checkin_item`
  ADD COLUMN IF NOT EXISTS `cosmetic_name` VARCHAR(128) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS `cosmetic_image` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `category` VARCHAR(32) NOT NULL DEFAULT 'skincare',
  ADD COLUMN IF NOT EXISTS `step_order` INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS `is_delete` INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `skin_test`
  ADD COLUMN IF NOT EXISTS `pore_score` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `blackhead_score` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `summary` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `advice` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `is_delete` INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
