server:
  port: 4001

spring:
  application:
    name: api_admin
  profiles:
    active: dev
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: ${MYSQL_USERNAME:root}
          password: ${MYSQL_ROOT_PASSWORD:}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${MYSQL_HOST:localhost}:${PORT_MYSQL:10020}/${MYSQL_DATABASE:tacomall}?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:10010}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:500}
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.baomidou: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.tacomall.common.mapper
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  configuration:
    call-setters-on-nulls: true

